name: Test Workflow

on: 
  push:
    branches:
      - main
      - development

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run a simple command
        run: echo "Hello, World! This is a test workflow."
